name: Run tests
on: push
jobs:
  run-shell-command:
    rusn-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depencencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: python -m unittest discover ./tests/tsukuda_fib_py
      - name: run type checking
        run: mypy tsukuda_fib_py
